spring:
    application:
        name: TransactionDemo

    cloud:
        config:
            import-check:
                enabled: false

    data:
        mongodb:
            uri: mongodb://109.123.244.12:30914/transaction?authSource=transaction&retryWrites=false
            database: transaction
            
        config:
            import: optional:configserver:http://localhost:8888

server:
    port: 8081

logging:
    level:
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG
        org.springframework.data.mongodb.core.query: TRACE